"""
Central WAF / block detection for active agents.

The problem this solves: agents used to infer "was my payload blocked?" from
ad-hoc, per-agent heuristics (SQLi checked ``status in (403,406,429)`` OR a
``200`` under 100 chars; most agents did not check at all). A WAF that answers
HTTP 200 with a block page ("Access Denied", a Cloudflare challenge, an Akamai
reference page) slipped through completely — so the agent never recorded a
``waf_block`` observation and the mutator never learned there was a defence to
bypass. A missed block is a missed bypass, which is a false negative.

This module centralises that decision. It recognises a block from:
  1. Classic block status codes (403/406/429/503/999).
  2. Content signatures of known block pages, EVEN on a 200 response.
  3. A collapse in response size vs. a known-good baseline (WAFs often replace a
     rich response with a short stub) — only used as a weak signal, alongside a
     status or content signal, never alone.

It never talks to the network and returns a small dataclass so callers can both
branch on ``is_block`` and feed ``signal`` straight into ``self.observe()``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Optional

# Status codes that, on their own, indicate the request was refused by an edge
# control rather than handled by the application. 999 is used by some WAFs.
_BLOCK_STATUS = frozenset({403, 406, 429, 503, 999})

# Content signatures of WAF / block pages. Matched case-insensitively against the
# response body prefix. These fire regardless of status code, so a WAF that
# returns "200 OK" with a block page is still caught. Kept intentionally specific
# to avoid flagging a legitimate app page that merely says "access denied" in a
# help article — each phrase is one a block page uses verbatim.
_BLOCK_CONTENT_SIGNATURES = (
    "access denied",
    "request blocked",
    "you have been blocked",
    "attention required",              # Cloudflare interstitial title
    "cloudflare to restrict access",
    "cf-error-details",
    "the requested url was rejected",  # F5 BIG-IP ASM
    "your support id is",              # F5 BIG-IP ASM
    "web application firewall",
    "blocked by",
    "malicious",
    "your request has been blocked",
    "unusual traffic",
    "bot detection",
    "please enable javascript and cookies",  # bot-mitigation challenge
    "incident id",                     # generic WAF block reference
    "reference #",                     # Akamai reference error
    "generated by cloudfront",
    "request unsuccessful. incapsula",
)

# Compiled once — matches any signature as a substring.
_BLOCK_CONTENT_RE = re.compile(
    "|".join(re.escape(sig) for sig in _BLOCK_CONTENT_SIGNATURES),
    re.IGNORECASE,
)

# A response that collapses to under this many chars, when a healthy baseline was
# much larger, is a weak block signal (WAF stub). Only trusted alongside another
# signal, never on its own.
_STUB_MAX_CHARS = 512
# The baseline must be at least this many times larger than the stub for the
# size-collapse heuristic to fire — avoids flagging naturally small responses.
_STUB_SHRINK_RATIO = 4


@dataclass(frozen=True)
class BlockVerdict:
    """Result of a block check. ``signal`` is a short human string for observe()."""
    is_block: bool
    reason: str = ""            # "status" | "content" | "size_collapse" | ""
    signal: str = ""            # ready to pass to VulnAgent.observe(signal=...)
    is_rate_limit: bool = False  # 429 specifically — callers may back off


def detect_block(
    status_code: int,
    body: str,
    baseline_len: Optional[int] = None,
) -> BlockVerdict:
    """
    Decide whether a probe response represents a WAF / edge block.

    Args:
        status_code: HTTP status of the probe response.
        body: response body text (only the prefix is inspected).
        baseline_len: length of a known-good response for this endpoint, if the
            caller has one — enables the size-collapse heuristic.

    Detection is deterministic and cheap. Content signatures win over status so
    a 200-with-block-page is reported with reason="content".
    """
    body_prefix = (body or "")[:2000]

    # 1. Content signature — strongest, works on any status (incl. 200).
    match = _BLOCK_CONTENT_RE.search(body_prefix)
    if match:
        return BlockVerdict(
            is_block=True,
            reason="content",
            signal=f"HTTP {status_code}: block-page signature {match.group(0)!r}",
            is_rate_limit=status_code == 429,
        )

    # 2. Classic block status code.
    if status_code in _BLOCK_STATUS:
        return BlockVerdict(
            is_block=True,
            reason="status",
            signal=f"HTTP {status_code}: {body_prefix[:100]}",
            is_rate_limit=status_code == 429,
        )

    # 3. Size collapse vs. a healthy baseline — weak, needs a real baseline and a
    #    genuinely large drop. Reported so the mutator knows a defence is active.
    if (
        baseline_len is not None
        and baseline_len >= _STUB_MAX_CHARS * _STUB_SHRINK_RATIO
        and len(body_prefix) < _STUB_MAX_CHARS
    ):
        return BlockVerdict(
            is_block=True,
            reason="size_collapse",
            signal=(
                f"HTTP {status_code}: response collapsed to {len(body_prefix)} chars "
                f"from ~{baseline_len} baseline (possible WAF stub)"
            ),
        )

    return BlockVerdict(is_block=False)
